name: Mapping (A)Ideology — main GPT results

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run GPT on the duplets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py iter1 1999
          tar -czvf results.tar.gz classified_*.csv
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: results.tar.gz
          tag_name: iter1_1999
